controller_manager:
  ros__parameters:
    update_rate: 100
    
    front_left_wheel_controller:
      type: velocity_controllers/JointVelocityController
      
    front_right_wheel_controller:
      type: velocity_controllers/JointVelocityController
      
    back_left_wheel_controller:
      type: velocity_controllers/JointVelocityController
      
    back_right_wheel_controller:
      type: velocity_controllers/JointVelocityController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

front_left_wheel_controller:
  ros__parameters:
    joint: front_left_wheel_joint
    
front_right_wheel_controller:
  ros__parameters:
    joint: front_right_wheel_joint
    
back_left_wheel_controller:
  ros__parameters:
    joint: back_left_wheel_joint
    
back_right_wheel_controller:
  ros__parameters:
    joint: back_right_wheel_joint